// -------------------------------------------------------------
//
// Module: filter_10k
// Generated by MATLAB(R) 9.7 and Filter Design HDL Coder 3.1.6.
// Generated on: 2021-11-11 03:51:42
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// TargetDirectory: E:\AM_PROJECT\gw2ademod
// Name: filter_10k
// SerialPartition: [64  64]
// TargetLanguage: Verilog
// TestBenchStimulus: impulse step ramp chirp noise 
// GenerateHDLTestBench: off

// -------------------------------------------------------------
// HDL Implementation    : Partly Serial
// Folding Factor        : 64
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time FIR Filter (real)
// -------------------------------
// Filter Structure  : Direct-Form FIR
// Filter Length     : 128
// Stable            : Yes
// Linear Phase      : Yes (Type 2)
// Arithmetic        : fixed
// Numerator         : s16,19 -> [-6.250000e-02 6.250000e-02)
// Input             : s12,11 -> [-1 1)
// Filter Internals  : Specify Precision
//   Output          : s15,14 -> [-1 1)
//   Product         : s31,32 -> [-2.500000e-01 2.500000e-01)
//   Accumulator     : s34,32 -> [-2 2)
//   Round Mode      : convergent
//   Overflow Mode   : wrap
// -------------------------------------------------------------




`timescale 1 ns / 1 ns

module filter_10k
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [11:0] filter_in; //sfix12_En11
  output  signed [14:0] filter_out; //sfix15_En14

////////////////////////////////////////////////////////////////
//Module Architecture: filter_10k
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [15:0] coeff1 = 16'b0000000011010000; //sfix16_En19
  parameter signed [15:0] coeff2 = 16'b0000000011010111; //sfix16_En19
  parameter signed [15:0] coeff3 = 16'b0000000011011101; //sfix16_En19
  parameter signed [15:0] coeff4 = 16'b0000000011100011; //sfix16_En19
  parameter signed [15:0] coeff5 = 16'b0000000011101000; //sfix16_En19
  parameter signed [15:0] coeff6 = 16'b0000000011101011; //sfix16_En19
  parameter signed [15:0] coeff7 = 16'b0000000011101011; //sfix16_En19
  parameter signed [15:0] coeff8 = 16'b0000000011100111; //sfix16_En19
  parameter signed [15:0] coeff9 = 16'b0000000011011101; //sfix16_En19
  parameter signed [15:0] coeff10 = 16'b0000000011001100; //sfix16_En19
  parameter signed [15:0] coeff11 = 16'b0000000010110011; //sfix16_En19
  parameter signed [15:0] coeff12 = 16'b0000000010010000; //sfix16_En19
  parameter signed [15:0] coeff13 = 16'b0000000001100000; //sfix16_En19
  parameter signed [15:0] coeff14 = 16'b0000000000100100; //sfix16_En19
  parameter signed [15:0] coeff15 = 16'b1111111111011001; //sfix16_En19
  parameter signed [15:0] coeff16 = 16'b1111111101111111; //sfix16_En19
  parameter signed [15:0] coeff17 = 16'b1111111100010101; //sfix16_En19
  parameter signed [15:0] coeff18 = 16'b1111111010011100; //sfix16_En19
  parameter signed [15:0] coeff19 = 16'b1111111000010100; //sfix16_En19
  parameter signed [15:0] coeff20 = 16'b1111110101111111; //sfix16_En19
  parameter signed [15:0] coeff21 = 16'b1111110011011110; //sfix16_En19
  parameter signed [15:0] coeff22 = 16'b1111110000110011; //sfix16_En19
  parameter signed [15:0] coeff23 = 16'b1111101110000011; //sfix16_En19
  parameter signed [15:0] coeff24 = 16'b1111101011010001; //sfix16_En19
  parameter signed [15:0] coeff25 = 16'b1111101000100001; //sfix16_En19
  parameter signed [15:0] coeff26 = 16'b1111100101111001; //sfix16_En19
  parameter signed [15:0] coeff27 = 16'b1111100011011111; //sfix16_En19
  parameter signed [15:0] coeff28 = 16'b1111100001011000; //sfix16_En19
  parameter signed [15:0] coeff29 = 16'b1111011111101011; //sfix16_En19
  parameter signed [15:0] coeff30 = 16'b1111011110100000; //sfix16_En19
  parameter signed [15:0] coeff31 = 16'b1111011101111100; //sfix16_En19
  parameter signed [15:0] coeff32 = 16'b1111011110001000; //sfix16_En19
  parameter signed [15:0] coeff33 = 16'b1111011111001000; //sfix16_En19
  parameter signed [15:0] coeff34 = 16'b1111100001000101; //sfix16_En19
  parameter signed [15:0] coeff35 = 16'b1111100100000100; //sfix16_En19
  parameter signed [15:0] coeff36 = 16'b1111101000001001; //sfix16_En19
  parameter signed [15:0] coeff37 = 16'b1111101101011001; //sfix16_En19
  parameter signed [15:0] coeff38 = 16'b1111110011111001; //sfix16_En19
  parameter signed [15:0] coeff39 = 16'b1111111011101001; //sfix16_En19
  parameter signed [15:0] coeff40 = 16'b0000000100101011; //sfix16_En19
  parameter signed [15:0] coeff41 = 16'b0000001111000000; //sfix16_En19
  parameter signed [15:0] coeff42 = 16'b0000011010100100; //sfix16_En19
  parameter signed [15:0] coeff43 = 16'b0000100111010110; //sfix16_En19
  parameter signed [15:0] coeff44 = 16'b0000110101010001; //sfix16_En19
  parameter signed [15:0] coeff45 = 16'b0001000100001111; //sfix16_En19
  parameter signed [15:0] coeff46 = 16'b0001010100001001; //sfix16_En19
  parameter signed [15:0] coeff47 = 16'b0001100100110110; //sfix16_En19
  parameter signed [15:0] coeff48 = 16'b0001110110001101; //sfix16_En19
  parameter signed [15:0] coeff49 = 16'b0010001000000010; //sfix16_En19
  parameter signed [15:0] coeff50 = 16'b0010011010001010; //sfix16_En19
  parameter signed [15:0] coeff51 = 16'b0010101100011000; //sfix16_En19
  parameter signed [15:0] coeff52 = 16'b0010111110011111; //sfix16_En19
  parameter signed [15:0] coeff53 = 16'b0011010000010001; //sfix16_En19
  parameter signed [15:0] coeff54 = 16'b0011100001100010; //sfix16_En19
  parameter signed [15:0] coeff55 = 16'b0011110010000010; //sfix16_En19
  parameter signed [15:0] coeff56 = 16'b0100000001100101; //sfix16_En19
  parameter signed [15:0] coeff57 = 16'b0100001111111110; //sfix16_En19
  parameter signed [15:0] coeff58 = 16'b0100011101000001; //sfix16_En19
  parameter signed [15:0] coeff59 = 16'b0100101000100011; //sfix16_En19
  parameter signed [15:0] coeff60 = 16'b0100110010011010; //sfix16_En19
  parameter signed [15:0] coeff61 = 16'b0100111010011101; //sfix16_En19
  parameter signed [15:0] coeff62 = 16'b0101000000100110; //sfix16_En19
  parameter signed [15:0] coeff63 = 16'b0101000100101111; //sfix16_En19
  parameter signed [15:0] coeff64 = 16'b0101000110110100; //sfix16_En19
  parameter signed [15:0] coeff65 = 16'b0101000110110100; //sfix16_En19
  parameter signed [15:0] coeff66 = 16'b0101000100101111; //sfix16_En19
  parameter signed [15:0] coeff67 = 16'b0101000000100110; //sfix16_En19
  parameter signed [15:0] coeff68 = 16'b0100111010011101; //sfix16_En19
  parameter signed [15:0] coeff69 = 16'b0100110010011010; //sfix16_En19
  parameter signed [15:0] coeff70 = 16'b0100101000100011; //sfix16_En19
  parameter signed [15:0] coeff71 = 16'b0100011101000001; //sfix16_En19
  parameter signed [15:0] coeff72 = 16'b0100001111111110; //sfix16_En19
  parameter signed [15:0] coeff73 = 16'b0100000001100101; //sfix16_En19
  parameter signed [15:0] coeff74 = 16'b0011110010000010; //sfix16_En19
  parameter signed [15:0] coeff75 = 16'b0011100001100010; //sfix16_En19
  parameter signed [15:0] coeff76 = 16'b0011010000010001; //sfix16_En19
  parameter signed [15:0] coeff77 = 16'b0010111110011111; //sfix16_En19
  parameter signed [15:0] coeff78 = 16'b0010101100011000; //sfix16_En19
  parameter signed [15:0] coeff79 = 16'b0010011010001010; //sfix16_En19
  parameter signed [15:0] coeff80 = 16'b0010001000000010; //sfix16_En19
  parameter signed [15:0] coeff81 = 16'b0001110110001101; //sfix16_En19
  parameter signed [15:0] coeff82 = 16'b0001100100110110; //sfix16_En19
  parameter signed [15:0] coeff83 = 16'b0001010100001001; //sfix16_En19
  parameter signed [15:0] coeff84 = 16'b0001000100001111; //sfix16_En19
  parameter signed [15:0] coeff85 = 16'b0000110101010001; //sfix16_En19
  parameter signed [15:0] coeff86 = 16'b0000100111010110; //sfix16_En19
  parameter signed [15:0] coeff87 = 16'b0000011010100100; //sfix16_En19
  parameter signed [15:0] coeff88 = 16'b0000001111000000; //sfix16_En19
  parameter signed [15:0] coeff89 = 16'b0000000100101011; //sfix16_En19
  parameter signed [15:0] coeff90 = 16'b1111111011101001; //sfix16_En19
  parameter signed [15:0] coeff91 = 16'b1111110011111001; //sfix16_En19
  parameter signed [15:0] coeff92 = 16'b1111101101011001; //sfix16_En19
  parameter signed [15:0] coeff93 = 16'b1111101000001001; //sfix16_En19
  parameter signed [15:0] coeff94 = 16'b1111100100000100; //sfix16_En19
  parameter signed [15:0] coeff95 = 16'b1111100001000101; //sfix16_En19
  parameter signed [15:0] coeff96 = 16'b1111011111001000; //sfix16_En19
  parameter signed [15:0] coeff97 = 16'b1111011110001000; //sfix16_En19
  parameter signed [15:0] coeff98 = 16'b1111011101111100; //sfix16_En19
  parameter signed [15:0] coeff99 = 16'b1111011110100000; //sfix16_En19
  parameter signed [15:0] coeff100 = 16'b1111011111101011; //sfix16_En19
  parameter signed [15:0] coeff101 = 16'b1111100001011000; //sfix16_En19
  parameter signed [15:0] coeff102 = 16'b1111100011011111; //sfix16_En19
  parameter signed [15:0] coeff103 = 16'b1111100101111001; //sfix16_En19
  parameter signed [15:0] coeff104 = 16'b1111101000100001; //sfix16_En19
  parameter signed [15:0] coeff105 = 16'b1111101011010001; //sfix16_En19
  parameter signed [15:0] coeff106 = 16'b1111101110000011; //sfix16_En19
  parameter signed [15:0] coeff107 = 16'b1111110000110011; //sfix16_En19
  parameter signed [15:0] coeff108 = 16'b1111110011011110; //sfix16_En19
  parameter signed [15:0] coeff109 = 16'b1111110101111111; //sfix16_En19
  parameter signed [15:0] coeff110 = 16'b1111111000010100; //sfix16_En19
  parameter signed [15:0] coeff111 = 16'b1111111010011100; //sfix16_En19
  parameter signed [15:0] coeff112 = 16'b1111111100010101; //sfix16_En19
  parameter signed [15:0] coeff113 = 16'b1111111101111111; //sfix16_En19
  parameter signed [15:0] coeff114 = 16'b1111111111011001; //sfix16_En19
  parameter signed [15:0] coeff115 = 16'b0000000000100100; //sfix16_En19
  parameter signed [15:0] coeff116 = 16'b0000000001100000; //sfix16_En19
  parameter signed [15:0] coeff117 = 16'b0000000010010000; //sfix16_En19
  parameter signed [15:0] coeff118 = 16'b0000000010110011; //sfix16_En19
  parameter signed [15:0] coeff119 = 16'b0000000011001100; //sfix16_En19
  parameter signed [15:0] coeff120 = 16'b0000000011011101; //sfix16_En19
  parameter signed [15:0] coeff121 = 16'b0000000011100111; //sfix16_En19
  parameter signed [15:0] coeff122 = 16'b0000000011101011; //sfix16_En19
  parameter signed [15:0] coeff123 = 16'b0000000011101011; //sfix16_En19
  parameter signed [15:0] coeff124 = 16'b0000000011101000; //sfix16_En19
  parameter signed [15:0] coeff125 = 16'b0000000011100011; //sfix16_En19
  parameter signed [15:0] coeff126 = 16'b0000000011011101; //sfix16_En19
  parameter signed [15:0] coeff127 = 16'b0000000011010111; //sfix16_En19
  parameter signed [15:0] coeff128 = 16'b0000000011010000; //sfix16_En19

  // Signals
  reg  [5:0] cur_count; // ufix6
  wire phase_63; // boolean
  wire phase_0; // boolean
  reg  signed [11:0] delay_pipeline [0:127] ; // sfix12_En11
  wire signed [11:0] inputmux_1; // sfix12_En11
  wire signed [11:0] inputmux_2; // sfix12_En11
  reg  signed [33:0] acc_final; // sfix34_En32
  reg  signed [33:0] acc_out_1; // sfix34_En32
  wire signed [30:0] product_1; // sfix31_En32
  wire signed [15:0] product_1_mux; // sfix16_En19
  wire signed [27:0] mul_temp; // sfix28_En30
  wire signed [33:0] prod_typeconvert_1; // sfix34_En32
  wire signed [33:0] acc_sum_1; // sfix34_En32
  wire signed [33:0] acc_in_1; // sfix34_En32
  wire signed [33:0] add_signext; // sfix34_En32
  wire signed [33:0] add_signext_1; // sfix34_En32
  wire signed [34:0] add_temp; // sfix35_En32
  reg  signed [33:0] acc_out_2; // sfix34_En32
  wire signed [30:0] product_2; // sfix31_En32
  wire signed [15:0] product_2_mux; // sfix16_En19
  wire signed [27:0] mul_temp_1; // sfix28_En30
  wire signed [33:0] prod_typeconvert_2; // sfix34_En32
  wire signed [33:0] acc_sum_2; // sfix34_En32
  wire signed [33:0] acc_in_2; // sfix34_En32
  wire signed [33:0] add_signext_2; // sfix34_En32
  wire signed [33:0] add_signext_3; // sfix34_En32
  wire signed [34:0] add_temp_1; // sfix35_En32
  wire signed [33:0] sum1; // sfix34_En32
  wire signed [33:0] add_signext_4; // sfix34_En32
  wire signed [33:0] add_signext_5; // sfix34_En32
  wire signed [34:0] add_temp_2; // sfix35_En32
  wire signed [14:0] output_typeconvert; // sfix15_En14
  reg  signed [14:0] output_register; // sfix15_En14

  // Block Statements
  always @ (posedge clk or posedge reset)
    begin: Counter_process
      if (reset == 1'b1) begin
        cur_count <= 6'b111111;
      end
      else begin
        if (clk_enable == 1'b1) begin
          if (cur_count >= 6'b111111) begin
            cur_count <= 6'b000000;
          end
          else begin
            cur_count <= cur_count + 6'b000001;
          end
        end
      end
    end // Counter_process

  assign  phase_63 = (cur_count == 6'b111111 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_0 = (cur_count == 6'b000000 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_process
      if (reset == 1'b1) begin
        delay_pipeline[0] <= 0;
        delay_pipeline[1] <= 0;
        delay_pipeline[2] <= 0;
        delay_pipeline[3] <= 0;
        delay_pipeline[4] <= 0;
        delay_pipeline[5] <= 0;
        delay_pipeline[6] <= 0;
        delay_pipeline[7] <= 0;
        delay_pipeline[8] <= 0;
        delay_pipeline[9] <= 0;
        delay_pipeline[10] <= 0;
        delay_pipeline[11] <= 0;
        delay_pipeline[12] <= 0;
        delay_pipeline[13] <= 0;
        delay_pipeline[14] <= 0;
        delay_pipeline[15] <= 0;
        delay_pipeline[16] <= 0;
        delay_pipeline[17] <= 0;
        delay_pipeline[18] <= 0;
        delay_pipeline[19] <= 0;
        delay_pipeline[20] <= 0;
        delay_pipeline[21] <= 0;
        delay_pipeline[22] <= 0;
        delay_pipeline[23] <= 0;
        delay_pipeline[24] <= 0;
        delay_pipeline[25] <= 0;
        delay_pipeline[26] <= 0;
        delay_pipeline[27] <= 0;
        delay_pipeline[28] <= 0;
        delay_pipeline[29] <= 0;
        delay_pipeline[30] <= 0;
        delay_pipeline[31] <= 0;
        delay_pipeline[32] <= 0;
        delay_pipeline[33] <= 0;
        delay_pipeline[34] <= 0;
        delay_pipeline[35] <= 0;
        delay_pipeline[36] <= 0;
        delay_pipeline[37] <= 0;
        delay_pipeline[38] <= 0;
        delay_pipeline[39] <= 0;
        delay_pipeline[40] <= 0;
        delay_pipeline[41] <= 0;
        delay_pipeline[42] <= 0;
        delay_pipeline[43] <= 0;
        delay_pipeline[44] <= 0;
        delay_pipeline[45] <= 0;
        delay_pipeline[46] <= 0;
        delay_pipeline[47] <= 0;
        delay_pipeline[48] <= 0;
        delay_pipeline[49] <= 0;
        delay_pipeline[50] <= 0;
        delay_pipeline[51] <= 0;
        delay_pipeline[52] <= 0;
        delay_pipeline[53] <= 0;
        delay_pipeline[54] <= 0;
        delay_pipeline[55] <= 0;
        delay_pipeline[56] <= 0;
        delay_pipeline[57] <= 0;
        delay_pipeline[58] <= 0;
        delay_pipeline[59] <= 0;
        delay_pipeline[60] <= 0;
        delay_pipeline[61] <= 0;
        delay_pipeline[62] <= 0;
        delay_pipeline[63] <= 0;
        delay_pipeline[64] <= 0;
        delay_pipeline[65] <= 0;
        delay_pipeline[66] <= 0;
        delay_pipeline[67] <= 0;
        delay_pipeline[68] <= 0;
        delay_pipeline[69] <= 0;
        delay_pipeline[70] <= 0;
        delay_pipeline[71] <= 0;
        delay_pipeline[72] <= 0;
        delay_pipeline[73] <= 0;
        delay_pipeline[74] <= 0;
        delay_pipeline[75] <= 0;
        delay_pipeline[76] <= 0;
        delay_pipeline[77] <= 0;
        delay_pipeline[78] <= 0;
        delay_pipeline[79] <= 0;
        delay_pipeline[80] <= 0;
        delay_pipeline[81] <= 0;
        delay_pipeline[82] <= 0;
        delay_pipeline[83] <= 0;
        delay_pipeline[84] <= 0;
        delay_pipeline[85] <= 0;
        delay_pipeline[86] <= 0;
        delay_pipeline[87] <= 0;
        delay_pipeline[88] <= 0;
        delay_pipeline[89] <= 0;
        delay_pipeline[90] <= 0;
        delay_pipeline[91] <= 0;
        delay_pipeline[92] <= 0;
        delay_pipeline[93] <= 0;
        delay_pipeline[94] <= 0;
        delay_pipeline[95] <= 0;
        delay_pipeline[96] <= 0;
        delay_pipeline[97] <= 0;
        delay_pipeline[98] <= 0;
        delay_pipeline[99] <= 0;
        delay_pipeline[100] <= 0;
        delay_pipeline[101] <= 0;
        delay_pipeline[102] <= 0;
        delay_pipeline[103] <= 0;
        delay_pipeline[104] <= 0;
        delay_pipeline[105] <= 0;
        delay_pipeline[106] <= 0;
        delay_pipeline[107] <= 0;
        delay_pipeline[108] <= 0;
        delay_pipeline[109] <= 0;
        delay_pipeline[110] <= 0;
        delay_pipeline[111] <= 0;
        delay_pipeline[112] <= 0;
        delay_pipeline[113] <= 0;
        delay_pipeline[114] <= 0;
        delay_pipeline[115] <= 0;
        delay_pipeline[116] <= 0;
        delay_pipeline[117] <= 0;
        delay_pipeline[118] <= 0;
        delay_pipeline[119] <= 0;
        delay_pipeline[120] <= 0;
        delay_pipeline[121] <= 0;
        delay_pipeline[122] <= 0;
        delay_pipeline[123] <= 0;
        delay_pipeline[124] <= 0;
        delay_pipeline[125] <= 0;
        delay_pipeline[126] <= 0;
        delay_pipeline[127] <= 0;
      end
      else begin
        if (phase_63 == 1'b1) begin
          delay_pipeline[0] <= filter_in;
          delay_pipeline[1] <= delay_pipeline[0];
          delay_pipeline[2] <= delay_pipeline[1];
          delay_pipeline[3] <= delay_pipeline[2];
          delay_pipeline[4] <= delay_pipeline[3];
          delay_pipeline[5] <= delay_pipeline[4];
          delay_pipeline[6] <= delay_pipeline[5];
          delay_pipeline[7] <= delay_pipeline[6];
          delay_pipeline[8] <= delay_pipeline[7];
          delay_pipeline[9] <= delay_pipeline[8];
          delay_pipeline[10] <= delay_pipeline[9];
          delay_pipeline[11] <= delay_pipeline[10];
          delay_pipeline[12] <= delay_pipeline[11];
          delay_pipeline[13] <= delay_pipeline[12];
          delay_pipeline[14] <= delay_pipeline[13];
          delay_pipeline[15] <= delay_pipeline[14];
          delay_pipeline[16] <= delay_pipeline[15];
          delay_pipeline[17] <= delay_pipeline[16];
          delay_pipeline[18] <= delay_pipeline[17];
          delay_pipeline[19] <= delay_pipeline[18];
          delay_pipeline[20] <= delay_pipeline[19];
          delay_pipeline[21] <= delay_pipeline[20];
          delay_pipeline[22] <= delay_pipeline[21];
          delay_pipeline[23] <= delay_pipeline[22];
          delay_pipeline[24] <= delay_pipeline[23];
          delay_pipeline[25] <= delay_pipeline[24];
          delay_pipeline[26] <= delay_pipeline[25];
          delay_pipeline[27] <= delay_pipeline[26];
          delay_pipeline[28] <= delay_pipeline[27];
          delay_pipeline[29] <= delay_pipeline[28];
          delay_pipeline[30] <= delay_pipeline[29];
          delay_pipeline[31] <= delay_pipeline[30];
          delay_pipeline[32] <= delay_pipeline[31];
          delay_pipeline[33] <= delay_pipeline[32];
          delay_pipeline[34] <= delay_pipeline[33];
          delay_pipeline[35] <= delay_pipeline[34];
          delay_pipeline[36] <= delay_pipeline[35];
          delay_pipeline[37] <= delay_pipeline[36];
          delay_pipeline[38] <= delay_pipeline[37];
          delay_pipeline[39] <= delay_pipeline[38];
          delay_pipeline[40] <= delay_pipeline[39];
          delay_pipeline[41] <= delay_pipeline[40];
          delay_pipeline[42] <= delay_pipeline[41];
          delay_pipeline[43] <= delay_pipeline[42];
          delay_pipeline[44] <= delay_pipeline[43];
          delay_pipeline[45] <= delay_pipeline[44];
          delay_pipeline[46] <= delay_pipeline[45];
          delay_pipeline[47] <= delay_pipeline[46];
          delay_pipeline[48] <= delay_pipeline[47];
          delay_pipeline[49] <= delay_pipeline[48];
          delay_pipeline[50] <= delay_pipeline[49];
          delay_pipeline[51] <= delay_pipeline[50];
          delay_pipeline[52] <= delay_pipeline[51];
          delay_pipeline[53] <= delay_pipeline[52];
          delay_pipeline[54] <= delay_pipeline[53];
          delay_pipeline[55] <= delay_pipeline[54];
          delay_pipeline[56] <= delay_pipeline[55];
          delay_pipeline[57] <= delay_pipeline[56];
          delay_pipeline[58] <= delay_pipeline[57];
          delay_pipeline[59] <= delay_pipeline[58];
          delay_pipeline[60] <= delay_pipeline[59];
          delay_pipeline[61] <= delay_pipeline[60];
          delay_pipeline[62] <= delay_pipeline[61];
          delay_pipeline[63] <= delay_pipeline[62];
          delay_pipeline[64] <= delay_pipeline[63];
          delay_pipeline[65] <= delay_pipeline[64];
          delay_pipeline[66] <= delay_pipeline[65];
          delay_pipeline[67] <= delay_pipeline[66];
          delay_pipeline[68] <= delay_pipeline[67];
          delay_pipeline[69] <= delay_pipeline[68];
          delay_pipeline[70] <= delay_pipeline[69];
          delay_pipeline[71] <= delay_pipeline[70];
          delay_pipeline[72] <= delay_pipeline[71];
          delay_pipeline[73] <= delay_pipeline[72];
          delay_pipeline[74] <= delay_pipeline[73];
          delay_pipeline[75] <= delay_pipeline[74];
          delay_pipeline[76] <= delay_pipeline[75];
          delay_pipeline[77] <= delay_pipeline[76];
          delay_pipeline[78] <= delay_pipeline[77];
          delay_pipeline[79] <= delay_pipeline[78];
          delay_pipeline[80] <= delay_pipeline[79];
          delay_pipeline[81] <= delay_pipeline[80];
          delay_pipeline[82] <= delay_pipeline[81];
          delay_pipeline[83] <= delay_pipeline[82];
          delay_pipeline[84] <= delay_pipeline[83];
          delay_pipeline[85] <= delay_pipeline[84];
          delay_pipeline[86] <= delay_pipeline[85];
          delay_pipeline[87] <= delay_pipeline[86];
          delay_pipeline[88] <= delay_pipeline[87];
          delay_pipeline[89] <= delay_pipeline[88];
          delay_pipeline[90] <= delay_pipeline[89];
          delay_pipeline[91] <= delay_pipeline[90];
          delay_pipeline[92] <= delay_pipeline[91];
          delay_pipeline[93] <= delay_pipeline[92];
          delay_pipeline[94] <= delay_pipeline[93];
          delay_pipeline[95] <= delay_pipeline[94];
          delay_pipeline[96] <= delay_pipeline[95];
          delay_pipeline[97] <= delay_pipeline[96];
          delay_pipeline[98] <= delay_pipeline[97];
          delay_pipeline[99] <= delay_pipeline[98];
          delay_pipeline[100] <= delay_pipeline[99];
          delay_pipeline[101] <= delay_pipeline[100];
          delay_pipeline[102] <= delay_pipeline[101];
          delay_pipeline[103] <= delay_pipeline[102];
          delay_pipeline[104] <= delay_pipeline[103];
          delay_pipeline[105] <= delay_pipeline[104];
          delay_pipeline[106] <= delay_pipeline[105];
          delay_pipeline[107] <= delay_pipeline[106];
          delay_pipeline[108] <= delay_pipeline[107];
          delay_pipeline[109] <= delay_pipeline[108];
          delay_pipeline[110] <= delay_pipeline[109];
          delay_pipeline[111] <= delay_pipeline[110];
          delay_pipeline[112] <= delay_pipeline[111];
          delay_pipeline[113] <= delay_pipeline[112];
          delay_pipeline[114] <= delay_pipeline[113];
          delay_pipeline[115] <= delay_pipeline[114];
          delay_pipeline[116] <= delay_pipeline[115];
          delay_pipeline[117] <= delay_pipeline[116];
          delay_pipeline[118] <= delay_pipeline[117];
          delay_pipeline[119] <= delay_pipeline[118];
          delay_pipeline[120] <= delay_pipeline[119];
          delay_pipeline[121] <= delay_pipeline[120];
          delay_pipeline[122] <= delay_pipeline[121];
          delay_pipeline[123] <= delay_pipeline[122];
          delay_pipeline[124] <= delay_pipeline[123];
          delay_pipeline[125] <= delay_pipeline[124];
          delay_pipeline[126] <= delay_pipeline[125];
          delay_pipeline[127] <= delay_pipeline[126];
        end
      end
    end // Delay_Pipeline_process


  assign inputmux_1 = (cur_count == 6'b000000) ? delay_pipeline[0] :
                     (cur_count == 6'b000001) ? delay_pipeline[1] :
                     (cur_count == 6'b000010) ? delay_pipeline[2] :
                     (cur_count == 6'b000011) ? delay_pipeline[3] :
                     (cur_count == 6'b000100) ? delay_pipeline[4] :
                     (cur_count == 6'b000101) ? delay_pipeline[5] :
                     (cur_count == 6'b000110) ? delay_pipeline[6] :
                     (cur_count == 6'b000111) ? delay_pipeline[7] :
                     (cur_count == 6'b001000) ? delay_pipeline[8] :
                     (cur_count == 6'b001001) ? delay_pipeline[9] :
                     (cur_count == 6'b001010) ? delay_pipeline[10] :
                     (cur_count == 6'b001011) ? delay_pipeline[11] :
                     (cur_count == 6'b001100) ? delay_pipeline[12] :
                     (cur_count == 6'b001101) ? delay_pipeline[13] :
                     (cur_count == 6'b001110) ? delay_pipeline[14] :
                     (cur_count == 6'b001111) ? delay_pipeline[15] :
                     (cur_count == 6'b010000) ? delay_pipeline[16] :
                     (cur_count == 6'b010001) ? delay_pipeline[17] :
                     (cur_count == 6'b010010) ? delay_pipeline[18] :
                     (cur_count == 6'b010011) ? delay_pipeline[19] :
                     (cur_count == 6'b010100) ? delay_pipeline[20] :
                     (cur_count == 6'b010101) ? delay_pipeline[21] :
                     (cur_count == 6'b010110) ? delay_pipeline[22] :
                     (cur_count == 6'b010111) ? delay_pipeline[23] :
                     (cur_count == 6'b011000) ? delay_pipeline[24] :
                     (cur_count == 6'b011001) ? delay_pipeline[25] :
                     (cur_count == 6'b011010) ? delay_pipeline[26] :
                     (cur_count == 6'b011011) ? delay_pipeline[27] :
                     (cur_count == 6'b011100) ? delay_pipeline[28] :
                     (cur_count == 6'b011101) ? delay_pipeline[29] :
                     (cur_count == 6'b011110) ? delay_pipeline[30] :
                     (cur_count == 6'b011111) ? delay_pipeline[31] :
                     (cur_count == 6'b100000) ? delay_pipeline[32] :
                     (cur_count == 6'b100001) ? delay_pipeline[33] :
                     (cur_count == 6'b100010) ? delay_pipeline[34] :
                     (cur_count == 6'b100011) ? delay_pipeline[35] :
                     (cur_count == 6'b100100) ? delay_pipeline[36] :
                     (cur_count == 6'b100101) ? delay_pipeline[37] :
                     (cur_count == 6'b100110) ? delay_pipeline[38] :
                     (cur_count == 6'b100111) ? delay_pipeline[39] :
                     (cur_count == 6'b101000) ? delay_pipeline[40] :
                     (cur_count == 6'b101001) ? delay_pipeline[41] :
                     (cur_count == 6'b101010) ? delay_pipeline[42] :
                     (cur_count == 6'b101011) ? delay_pipeline[43] :
                     (cur_count == 6'b101100) ? delay_pipeline[44] :
                     (cur_count == 6'b101101) ? delay_pipeline[45] :
                     (cur_count == 6'b101110) ? delay_pipeline[46] :
                     (cur_count == 6'b101111) ? delay_pipeline[47] :
                     (cur_count == 6'b110000) ? delay_pipeline[48] :
                     (cur_count == 6'b110001) ? delay_pipeline[49] :
                     (cur_count == 6'b110010) ? delay_pipeline[50] :
                     (cur_count == 6'b110011) ? delay_pipeline[51] :
                     (cur_count == 6'b110100) ? delay_pipeline[52] :
                     (cur_count == 6'b110101) ? delay_pipeline[53] :
                     (cur_count == 6'b110110) ? delay_pipeline[54] :
                     (cur_count == 6'b110111) ? delay_pipeline[55] :
                     (cur_count == 6'b111000) ? delay_pipeline[56] :
                     (cur_count == 6'b111001) ? delay_pipeline[57] :
                     (cur_count == 6'b111010) ? delay_pipeline[58] :
                     (cur_count == 6'b111011) ? delay_pipeline[59] :
                     (cur_count == 6'b111100) ? delay_pipeline[60] :
                     (cur_count == 6'b111101) ? delay_pipeline[61] :
                     (cur_count == 6'b111110) ? delay_pipeline[62] :
                     delay_pipeline[63];

  assign inputmux_2 = (cur_count == 6'b000000) ? delay_pipeline[64] :
                     (cur_count == 6'b000001) ? delay_pipeline[65] :
                     (cur_count == 6'b000010) ? delay_pipeline[66] :
                     (cur_count == 6'b000011) ? delay_pipeline[67] :
                     (cur_count == 6'b000100) ? delay_pipeline[68] :
                     (cur_count == 6'b000101) ? delay_pipeline[69] :
                     (cur_count == 6'b000110) ? delay_pipeline[70] :
                     (cur_count == 6'b000111) ? delay_pipeline[71] :
                     (cur_count == 6'b001000) ? delay_pipeline[72] :
                     (cur_count == 6'b001001) ? delay_pipeline[73] :
                     (cur_count == 6'b001010) ? delay_pipeline[74] :
                     (cur_count == 6'b001011) ? delay_pipeline[75] :
                     (cur_count == 6'b001100) ? delay_pipeline[76] :
                     (cur_count == 6'b001101) ? delay_pipeline[77] :
                     (cur_count == 6'b001110) ? delay_pipeline[78] :
                     (cur_count == 6'b001111) ? delay_pipeline[79] :
                     (cur_count == 6'b010000) ? delay_pipeline[80] :
                     (cur_count == 6'b010001) ? delay_pipeline[81] :
                     (cur_count == 6'b010010) ? delay_pipeline[82] :
                     (cur_count == 6'b010011) ? delay_pipeline[83] :
                     (cur_count == 6'b010100) ? delay_pipeline[84] :
                     (cur_count == 6'b010101) ? delay_pipeline[85] :
                     (cur_count == 6'b010110) ? delay_pipeline[86] :
                     (cur_count == 6'b010111) ? delay_pipeline[87] :
                     (cur_count == 6'b011000) ? delay_pipeline[88] :
                     (cur_count == 6'b011001) ? delay_pipeline[89] :
                     (cur_count == 6'b011010) ? delay_pipeline[90] :
                     (cur_count == 6'b011011) ? delay_pipeline[91] :
                     (cur_count == 6'b011100) ? delay_pipeline[92] :
                     (cur_count == 6'b011101) ? delay_pipeline[93] :
                     (cur_count == 6'b011110) ? delay_pipeline[94] :
                     (cur_count == 6'b011111) ? delay_pipeline[95] :
                     (cur_count == 6'b100000) ? delay_pipeline[96] :
                     (cur_count == 6'b100001) ? delay_pipeline[97] :
                     (cur_count == 6'b100010) ? delay_pipeline[98] :
                     (cur_count == 6'b100011) ? delay_pipeline[99] :
                     (cur_count == 6'b100100) ? delay_pipeline[100] :
                     (cur_count == 6'b100101) ? delay_pipeline[101] :
                     (cur_count == 6'b100110) ? delay_pipeline[102] :
                     (cur_count == 6'b100111) ? delay_pipeline[103] :
                     (cur_count == 6'b101000) ? delay_pipeline[104] :
                     (cur_count == 6'b101001) ? delay_pipeline[105] :
                     (cur_count == 6'b101010) ? delay_pipeline[106] :
                     (cur_count == 6'b101011) ? delay_pipeline[107] :
                     (cur_count == 6'b101100) ? delay_pipeline[108] :
                     (cur_count == 6'b101101) ? delay_pipeline[109] :
                     (cur_count == 6'b101110) ? delay_pipeline[110] :
                     (cur_count == 6'b101111) ? delay_pipeline[111] :
                     (cur_count == 6'b110000) ? delay_pipeline[112] :
                     (cur_count == 6'b110001) ? delay_pipeline[113] :
                     (cur_count == 6'b110010) ? delay_pipeline[114] :
                     (cur_count == 6'b110011) ? delay_pipeline[115] :
                     (cur_count == 6'b110100) ? delay_pipeline[116] :
                     (cur_count == 6'b110101) ? delay_pipeline[117] :
                     (cur_count == 6'b110110) ? delay_pipeline[118] :
                     (cur_count == 6'b110111) ? delay_pipeline[119] :
                     (cur_count == 6'b111000) ? delay_pipeline[120] :
                     (cur_count == 6'b111001) ? delay_pipeline[121] :
                     (cur_count == 6'b111010) ? delay_pipeline[122] :
                     (cur_count == 6'b111011) ? delay_pipeline[123] :
                     (cur_count == 6'b111100) ? delay_pipeline[124] :
                     (cur_count == 6'b111101) ? delay_pipeline[125] :
                     (cur_count == 6'b111110) ? delay_pipeline[126] :
                     delay_pipeline[127];

  //   ------------------ Serial partition # 1 ------------------

  assign product_1_mux = (cur_count == 6'b000000) ? coeff1 :
                        (cur_count == 6'b000001) ? coeff2 :
                        (cur_count == 6'b000010) ? coeff3 :
                        (cur_count == 6'b000011) ? coeff4 :
                        (cur_count == 6'b000100) ? coeff5 :
                        (cur_count == 6'b000101) ? coeff6 :
                        (cur_count == 6'b000110) ? coeff7 :
                        (cur_count == 6'b000111) ? coeff8 :
                        (cur_count == 6'b001000) ? coeff9 :
                        (cur_count == 6'b001001) ? coeff10 :
                        (cur_count == 6'b001010) ? coeff11 :
                        (cur_count == 6'b001011) ? coeff12 :
                        (cur_count == 6'b001100) ? coeff13 :
                        (cur_count == 6'b001101) ? coeff14 :
                        (cur_count == 6'b001110) ? coeff15 :
                        (cur_count == 6'b001111) ? coeff16 :
                        (cur_count == 6'b010000) ? coeff17 :
                        (cur_count == 6'b010001) ? coeff18 :
                        (cur_count == 6'b010010) ? coeff19 :
                        (cur_count == 6'b010011) ? coeff20 :
                        (cur_count == 6'b010100) ? coeff21 :
                        (cur_count == 6'b010101) ? coeff22 :
                        (cur_count == 6'b010110) ? coeff23 :
                        (cur_count == 6'b010111) ? coeff24 :
                        (cur_count == 6'b011000) ? coeff25 :
                        (cur_count == 6'b011001) ? coeff26 :
                        (cur_count == 6'b011010) ? coeff27 :
                        (cur_count == 6'b011011) ? coeff28 :
                        (cur_count == 6'b011100) ? coeff29 :
                        (cur_count == 6'b011101) ? coeff30 :
                        (cur_count == 6'b011110) ? coeff31 :
                        (cur_count == 6'b011111) ? coeff32 :
                        (cur_count == 6'b100000) ? coeff33 :
                        (cur_count == 6'b100001) ? coeff34 :
                        (cur_count == 6'b100010) ? coeff35 :
                        (cur_count == 6'b100011) ? coeff36 :
                        (cur_count == 6'b100100) ? coeff37 :
                        (cur_count == 6'b100101) ? coeff38 :
                        (cur_count == 6'b100110) ? coeff39 :
                        (cur_count == 6'b100111) ? coeff40 :
                        (cur_count == 6'b101000) ? coeff41 :
                        (cur_count == 6'b101001) ? coeff42 :
                        (cur_count == 6'b101010) ? coeff43 :
                        (cur_count == 6'b101011) ? coeff44 :
                        (cur_count == 6'b101100) ? coeff45 :
                        (cur_count == 6'b101101) ? coeff46 :
                        (cur_count == 6'b101110) ? coeff47 :
                        (cur_count == 6'b101111) ? coeff48 :
                        (cur_count == 6'b110000) ? coeff49 :
                        (cur_count == 6'b110001) ? coeff50 :
                        (cur_count == 6'b110010) ? coeff51 :
                        (cur_count == 6'b110011) ? coeff52 :
                        (cur_count == 6'b110100) ? coeff53 :
                        (cur_count == 6'b110101) ? coeff54 :
                        (cur_count == 6'b110110) ? coeff55 :
                        (cur_count == 6'b110111) ? coeff56 :
                        (cur_count == 6'b111000) ? coeff57 :
                        (cur_count == 6'b111001) ? coeff58 :
                        (cur_count == 6'b111010) ? coeff59 :
                        (cur_count == 6'b111011) ? coeff60 :
                        (cur_count == 6'b111100) ? coeff61 :
                        (cur_count == 6'b111101) ? coeff62 :
                        (cur_count == 6'b111110) ? coeff63 :
                        coeff64;
  assign mul_temp = inputmux_1 * product_1_mux;
  assign product_1 = $signed({mul_temp[27:0], 2'b00});

  assign prod_typeconvert_1 = $signed({{3{product_1[30]}}, product_1});

  assign add_signext = prod_typeconvert_1;
  assign add_signext_1 = acc_out_1;
  assign add_temp = add_signext + add_signext_1;
  assign acc_sum_1 = add_temp[33:0];

  assign acc_in_1 = (phase_0 == 1'b1) ? prod_typeconvert_1 :
                   acc_sum_1;

  always @ (posedge clk or posedge reset)
    begin: Acc_reg_1_process
      if (reset == 1'b1) begin
        acc_out_1 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          acc_out_1 <= acc_in_1;
        end
      end
    end // Acc_reg_1_process

  //   ------------------ Serial partition # 2 ------------------

  assign product_2_mux = (cur_count == 6'b000000) ? coeff65 :
                        (cur_count == 6'b000001) ? coeff66 :
                        (cur_count == 6'b000010) ? coeff67 :
                        (cur_count == 6'b000011) ? coeff68 :
                        (cur_count == 6'b000100) ? coeff69 :
                        (cur_count == 6'b000101) ? coeff70 :
                        (cur_count == 6'b000110) ? coeff71 :
                        (cur_count == 6'b000111) ? coeff72 :
                        (cur_count == 6'b001000) ? coeff73 :
                        (cur_count == 6'b001001) ? coeff74 :
                        (cur_count == 6'b001010) ? coeff75 :
                        (cur_count == 6'b001011) ? coeff76 :
                        (cur_count == 6'b001100) ? coeff77 :
                        (cur_count == 6'b001101) ? coeff78 :
                        (cur_count == 6'b001110) ? coeff79 :
                        (cur_count == 6'b001111) ? coeff80 :
                        (cur_count == 6'b010000) ? coeff81 :
                        (cur_count == 6'b010001) ? coeff82 :
                        (cur_count == 6'b010010) ? coeff83 :
                        (cur_count == 6'b010011) ? coeff84 :
                        (cur_count == 6'b010100) ? coeff85 :
                        (cur_count == 6'b010101) ? coeff86 :
                        (cur_count == 6'b010110) ? coeff87 :
                        (cur_count == 6'b010111) ? coeff88 :
                        (cur_count == 6'b011000) ? coeff89 :
                        (cur_count == 6'b011001) ? coeff90 :
                        (cur_count == 6'b011010) ? coeff91 :
                        (cur_count == 6'b011011) ? coeff92 :
                        (cur_count == 6'b011100) ? coeff93 :
                        (cur_count == 6'b011101) ? coeff94 :
                        (cur_count == 6'b011110) ? coeff95 :
                        (cur_count == 6'b011111) ? coeff96 :
                        (cur_count == 6'b100000) ? coeff97 :
                        (cur_count == 6'b100001) ? coeff98 :
                        (cur_count == 6'b100010) ? coeff99 :
                        (cur_count == 6'b100011) ? coeff100 :
                        (cur_count == 6'b100100) ? coeff101 :
                        (cur_count == 6'b100101) ? coeff102 :
                        (cur_count == 6'b100110) ? coeff103 :
                        (cur_count == 6'b100111) ? coeff104 :
                        (cur_count == 6'b101000) ? coeff105 :
                        (cur_count == 6'b101001) ? coeff106 :
                        (cur_count == 6'b101010) ? coeff107 :
                        (cur_count == 6'b101011) ? coeff108 :
                        (cur_count == 6'b101100) ? coeff109 :
                        (cur_count == 6'b101101) ? coeff110 :
                        (cur_count == 6'b101110) ? coeff111 :
                        (cur_count == 6'b101111) ? coeff112 :
                        (cur_count == 6'b110000) ? coeff113 :
                        (cur_count == 6'b110001) ? coeff114 :
                        (cur_count == 6'b110010) ? coeff115 :
                        (cur_count == 6'b110011) ? coeff116 :
                        (cur_count == 6'b110100) ? coeff117 :
                        (cur_count == 6'b110101) ? coeff118 :
                        (cur_count == 6'b110110) ? coeff119 :
                        (cur_count == 6'b110111) ? coeff120 :
                        (cur_count == 6'b111000) ? coeff121 :
                        (cur_count == 6'b111001) ? coeff122 :
                        (cur_count == 6'b111010) ? coeff123 :
                        (cur_count == 6'b111011) ? coeff124 :
                        (cur_count == 6'b111100) ? coeff125 :
                        (cur_count == 6'b111101) ? coeff126 :
                        (cur_count == 6'b111110) ? coeff127 :
                        coeff128;
  assign mul_temp_1 = inputmux_2 * product_2_mux;
  assign product_2 = $signed({mul_temp_1[27:0], 2'b00});

  assign prod_typeconvert_2 = $signed({{3{product_2[30]}}, product_2});

  assign add_signext_2 = prod_typeconvert_2;
  assign add_signext_3 = acc_out_2;
  assign add_temp_1 = add_signext_2 + add_signext_3;
  assign acc_sum_2 = add_temp_1[33:0];

  assign acc_in_2 = (phase_0 == 1'b1) ? prod_typeconvert_2 :
                   acc_sum_2;

  always @ (posedge clk or posedge reset)
    begin: Acc_reg_2_process
      if (reset == 1'b1) begin
        acc_out_2 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          acc_out_2 <= acc_in_2;
        end
      end
    end // Acc_reg_2_process

  assign add_signext_4 = acc_out_2;
  assign add_signext_5 = acc_out_1;
  assign add_temp_2 = add_signext_4 + add_signext_5;
  assign sum1 = add_temp_2[33:0];

  always @ (posedge clk or posedge reset)
    begin: Finalsum_reg_process
      if (reset == 1'b1) begin
        acc_final <= 0;
      end
      else begin
        if (phase_0 == 1'b1) begin
          acc_final <= sum1;
        end
      end
    end // Finalsum_reg_process

  assign output_typeconvert = (acc_final[32:0] + {acc_final[18], {17{~acc_final[18]}}})>>>18;

  always @ (posedge clk or posedge reset)
    begin: Output_Register_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (phase_63 == 1'b1) begin
          output_register <= output_typeconvert;
        end
      end
    end // Output_Register_process

  // Assignment Statements
  assign filter_out = output_register;
endmodule  // filter_10k
